accounts:
  - name: user1
    coins: ["4000000000stake"]
validator:
  name: user1
  staked: "1000000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
# genesis:
#   chain_id: "martian"
#   app_state:
#     staking:
#       params:
#         bond_denom: "martian"
